<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Services\I18n\LangFileWriter;
use App\Services\I18n\TranslationCostTracker;
use App\Services\I18n\TranslationDriverFactory;
use App\Services\I18n\TranslationSuggestionService;
use App\Support\LangBundleLoader;
use Illuminate\Console\Command;

/**
 * Phase-43 LANG-AUDIT-3 / Phase-52 APPLY-WORKFLOW-1: emit suggested
 * translations for missing keys in a namespace.
 *
 * Default mode prints a ready-to-paste PHP array fragment. --apply
 * atomically writes the suggestions into lang/<locale>/<namespace>.php
 * via LangFileWriter (which backs up the prior content + deep-merges
 * so existing keys are never clobbered).
 */
class LangSuggest extends Command
{
    protected $signature = 'lang:suggest {namespace} {--source=en} {--target=sw} {--driver=} {--apply}';

    protected $description = 'Phase-43 LANG-AUDIT-3 / Phase-52 APPLY-WORKFLOW-1: emit suggested translations; --apply writes them to disk.';

    public function handle(LangBundleLoader $loader, LangFileWriter $writer): int
    {
        $namespace = (string) $this->argument('namespace');
        $sourceLocale = (string) $this->option('source');
        $targetLocale = (string) $this->option('target');
        $driverOverride = $this->option('driver');
        $apply = (bool) $this->option('apply');

        $source = $loader->load($sourceLocale);
        $sourceSection = $source[$namespace] ?? null;
        if (! is_array($sourceSection)) {
            $this->error("Namespace `{$namespace}` not found in `{$sourceLocale}` bundle.");

            return self::FAILURE;
        }

        $target = $loader->load($targetLocale);
        $targetSection = is_array($target[$namespace] ?? null) ? $target[$namespace] : [];

        $factory = new TranslationDriverFactory(new TranslationCostTracker());
        $service = $driverOverride !== null
            ? new TranslationSuggestionService($factory->make((string) $driverOverride))
            : TranslationSuggestionService::fromConfig($factory);

        $sourceKeys = $loader->flatten($sourceSection, $namespace);
        $targetKeys = $loader->flatten($targetSection, $namespace);
        $missing = array_values(array_diff($sourceKeys, $targetKeys));

        if ($missing === []) {
            $this->info("No missing keys for {$targetLocale}/{$namespace}.");

            return self::SUCCESS;
        }

        $suggestions = [];
        foreach ($missing as $dottedKey) {
            $segments = explode('.', $dottedKey);
            array_shift($segments); // drop namespace prefix
            $sourceValue = $this->dataGet($sourceSection, $segments);
            if (! is_string($sourceValue)) {
                continue;
            }
            $translation = $service->suggest($sourceValue, $sourceLocale, $targetLocale);
            $this->setNested($suggestions, $segments, $translation);
        }

        if ($apply) {
            return $this->applyToLangFile($writer, $targetLocale, $namespace, $targetSection, $suggestions, $service->driverName());
        }

        return $this->printFragment($targetLocale, $namespace, $suggestions);
    }

    /**
     * @param  array<string, mixed>  $suggestions
     */
    private function applyToLangFile(
        LangFileWriter $writer,
        string $targetLocale,
        string $namespace,
        array $existingSection,
        array $suggestions,
        string $driverName,
    ): int {
        $path = base_path("lang/{$targetLocale}/{$namespace}.php");
        $existing = $writer->load($path);
        // The bundle loader handles 1-level-deep namespacing; the lang
        // file itself returns the inner array — match that shape.
        $merged = $writer->merge(
            $existingSection !== [] ? $existing : $existing,
            $suggestions,
        );

        $writer->write(
            $path,
            $merged,
            "Auto-generated by lang:suggest --driver={$driverName} (Phase-52 APPLY-WORKFLOW-1).",
        );

        $this->info("Wrote " . count($this->flat($suggestions)) . " suggestion(s) into {$path}");

        return self::SUCCESS;
    }

    /**
     * @param  array<string, mixed>  $suggestions
     */
    private function printFragment(string $targetLocale, string $namespace, array $suggestions): int
    {
        $this->line('<?php');
        $this->line("// Suggestions for lang/{$targetLocale}/{$namespace}.php (Phase-43 LANG-AUDIT-3 stub output).");
        $this->line("// Replace each [TODO:{$targetLocale}] line with the human translation.");
        $this->line('return [');
        foreach ($this->flat($suggestions) as $key => $val) {
            $escaped = addcslashes((string) $val, "\\'");
            $this->line(sprintf("    '%s' => '%s',", $key, $escaped));
        }
        $this->line('];');

        return self::SUCCESS;
    }

    /**
     * @param  array<int, string>  $segments
     */
    private function dataGet(array $haystack, array $segments): mixed
    {
        $cursor = $haystack;
        foreach ($segments as $segment) {
            if (! is_array($cursor) || ! array_key_exists($segment, $cursor)) {
                return null;
            }
            $cursor = $cursor[$segment];
        }

        return $cursor;
    }

    /**
     * @param  array<int, string>  $segments
     */
    private function setNested(array &$target, array $segments, mixed $value): void
    {
        $cursor = &$target;
        $last = array_pop($segments);
        foreach ($segments as $segment) {
            if (! isset($cursor[$segment]) || ! is_array($cursor[$segment])) {
                $cursor[$segment] = [];
            }
            $cursor = &$cursor[$segment];
        }
        $cursor[$last] = $value;
    }

    /**
     * @return array<string, string>
     */
    private function flat(array $source, string $prefix = ''): array
    {
        $out = [];
        foreach ($source as $k => $v) {
            $path = $prefix === '' ? (string) $k : "{$prefix}.{$k}";
            if (is_array($v)) {
                foreach ($this->flat($v, $path) as $kk => $vv) {
                    $out[$kk] = $vv;
                }

                continue;
            }
            $out[$path] = (string) $v;
        }

        return $out;
    }
}
