<?php

return [

    /*
    |--------------------------------------------------------------------------
    | PDF Template Strings
    |--------------------------------------------------------------------------
    |
    | All user-facing strings used in PDF templates.
    | Organized by document type for maintainability.
    |
    */

    'invoice' => [
        'title' => 'INVOICE',
        'from' => 'From',
        'bill_to' => 'Bill To',
        'unit' => 'Unit :number',
        'invoice_date' => 'Invoice Date:',
        'due_date' => 'Due Date:',
        'billing_period' => 'Billing Period:',
        'status' => 'Status:',
        'description' => 'Description',
        'amount' => 'Amount (KES)',
        'monthly_rent' => 'Monthly Rent',
        'water_charges' => 'Water Charges',
        'previous_arrears' => 'Previous Arrears',
        'subtotal' => 'Subtotal:',
        'amount_paid' => 'Amount Paid:',
        'balance_due' => 'Balance Due:',
        'amount_due' => 'Amount Due',
        'payment_instructions' => 'Payment Instructions',
        'mpesa_instruction' => 'Pay via Lipa Na M-Pesa using Paybill/Till number provided by your landlord',
        'bank_instruction' => 'Transfer to the bank account provided by your landlord',
        'online_instruction' => 'Pay securely through the tenant portal',
        'generated_on' => 'Generated on :date',
        'footer_generated' => 'This invoice was generated by PropManager',
        'footer_contact' => 'For inquiries, please contact your property manager',
    ],

    'credit_note' => [
        'title' => 'CREDIT NOTE',
        'credit_adjustment' => 'Credit Adjustment',
        'credit_amount' => 'Credit Amount',
        'applied' => 'Applied',
        'remaining' => 'Remaining',
        'credit_issued_to' => 'Credit Issued To',
        'tenant' => 'Tenant',
        'property' => 'Property',
        'reason_for_credit' => 'Reason for Credit',
        'original_invoice_reference' => 'Original Invoice Reference',
        'invoice_number' => 'Invoice Number',
        'invoice_date' => 'Invoice Date',
        'invoice_amount' => 'Invoice Amount',
        'approval_details' => 'Approval Details',
        'approved_by' => 'Approved By',
        'approved_date' => 'Approved Date',
        'application_details' => 'Application Details',
        'applied_to_invoice' => 'Applied To Invoice',
        'amount_applied' => 'Amount Applied',
        'applied_date' => 'Applied Date',
        'balance_summary' => 'Balance Summary',
        'credit_note_amount' => 'Credit Note Amount',
        'available_credit' => 'Available Credit',
        'terms_title' => 'Terms & Conditions',
        'term_valid' => 'This credit note is valid for application against future invoices.',
        'term_no_cash' => 'Credit notes cannot be redeemed for cash.',
        'term_tenancy' => 'This credit note must be used within the tenancy period.',
        'term_contact' => 'Contact your property manager for any queries regarding this credit note.',
        'footer' => 'This is an official credit note issued by :business',
        'generated_on' => 'Generated on :date',
    ],

    'receipt' => [
        'title' => 'RECEIPT',
        'payment_receipt' => 'Payment Receipt',
        'receipt_number' => 'Receipt Number',
        'payment_date' => 'Payment Date',
        'received_from' => 'Received From',
        'payment_for' => 'Payment For',
        'amount_received' => 'Amount Received',
        'payment_method' => 'Payment Method',
        'reference' => 'Reference',
        'invoice_details' => 'Invoice Details',
        'balance_after_payment' => 'Balance After Payment',
        'full_payment' => 'Full Payment',
        'partial_payment' => 'Partial Payment',
        'thank_you' => 'Thank you for your payment!',
        'footer' => 'This is an official receipt',
        'generated_on' => 'Generated on :date',
    ],

    'ledger' => [
        'title' => 'TENANT LEDGER',
        'statement' => 'Statement',
        'account_summary' => 'Account Summary',
        'tenant_details' => 'Tenant Details',
        'period' => 'Period',
        'opening_balance' => 'Opening Balance',
        'closing_balance' => 'Closing Balance',
        'transactions' => 'Transactions',
        'date' => 'Date',
        'description' => 'Description',
        'debit' => 'Debit',
        'credit' => 'Credit',
        'balance' => 'Balance',
        'total_debits' => 'Total Debits',
        'total_credits' => 'Total Credits',
        'footer' => 'This statement is for informational purposes only',
    ],

    'common' => [
        'currency' => 'KES',
        'page' => 'Page :current of :total',
        'generated_by' => 'Generated by PropManager',
        'confidential' => 'Confidential',
    ],

];
