<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Arrears Analysis Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #DC2626;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #DC2626;
            font-size: 24px;
        }
        .meta {
            text-align: right;
            font-size: 10px;
            color: #666;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            background-color: #FEE2E2;
            padding: 8px;
            margin: 0 0 15px 0;
            font-size: 14px;
            border-left: 4px solid #DC2626;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #E5E7EB;
        }
        th {
            background-color: #F9FAFB;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .text-red {
            color: #DC2626;
        }
        .alert-box {
            background-color: #FEF2F2;
            border: 1px solid #FCA5A5;
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 4px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #E5E7EB;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Arrears Analysis Report</h1>
        <p>{{ $landlord->name }}</p>
    </div>

    <div class="meta">
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="alert-box">
        <strong>Total Arrears:</strong> {{ $currency_symbol }} {{ number_format($data['summary']['total_arrears'], 2) }}<br>
        <strong>Overdue Invoices:</strong> {{ $data['summary']['count'] }} invoice(s)
    </div>

    <div class="section">
        <h2>Aging Analysis</h2>
        <table>
            <tr>
                <th>Aging Period</th>
                <th class="text-right">Amount ({{ $currency_code }})</th>
                <th class="text-right">Percentage</th>
            </tr>
            @foreach($data['aging_breakdown'] as $period => $amount)
            <tr>
                <td>{{ $period }} days</td>
                <td class="text-right text-red">{{ number_format($amount, 2) }}</td>
                <td class="text-right">{{ $data['summary']['total_arrears'] > 0 ? round(($amount / $data['summary']['total_arrears']) * 100, 1) : 0 }}%</td>
            </tr>
            @endforeach
        </table>
    </div>

    @if(count($data['details']) > 0)
    <div class="section">
        <h2>Detailed Arrears List</h2>
        <table>
            <tr>
                <th>Unit</th>
                <th>Tenant</th>
                <th>Invoice Number</th>
                <th class="text-center">Days Overdue</th>
                <th class="text-right">Amount ({{ $currency_code }})</th>
            </tr>
            @foreach($data['details'] as $detail)
            <tr>
                <td>{{ $detail['unit'] }}</td>
                <td>{{ $detail['tenant'] }}</td>
                <td>{{ $detail['invoice_number'] }}</td>
                <td class="text-center">{{ $detail['days_overdue'] }}</td>
                <td class="text-right text-red">{{ number_format($detail['amount'], 2) }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    @endif

    <div class="footer">
        <p>Generated by PropManager - Property Management System</p>
        <p><strong>ACTION REQUIRED:</strong> Please follow up with overdue accounts immediately.</p>
    </div>
</body>
</html>
