<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Occupancy Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4F46E5;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #4F46E5;
            font-size: 24px;
        }
        .meta {
            text-align: right;
            font-size: 10px;
            color: #666;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            background-color: #F3F4F6;
            padding: 8px;
            margin: 0 0 15px 0;
            font-size: 14px;
            border-left: 4px solid #4F46E5;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #E5E7EB;
        }
        th {
            background-color: #F9FAFB;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .text-green {
            color: #059669;
        }
        .highlight {
            background-color: #FEF3C7;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #E5E7EB;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Occupancy Report</h1>
        <p>{{ $landlord->name }}</p>
    </div>

    <div class="meta">
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="section">
        <h2>Occupancy Summary</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th class="text-right">Count</th>
                <th class="text-right">Percentage</th>
            </tr>
            <tr>
                <td>Total Units</td>
                <td class="text-right">{{ $data['summary']['total_units'] }}</td>
                <td class="text-right">100%</td>
            </tr>
            <tr class="text-green">
                <td>Occupied Units</td>
                <td class="text-right">{{ $data['summary']['occupied'] }}</td>
                <td class="text-right">{{ $data['summary']['occupancy_rate'] }}%</td>
            </tr>
            <tr>
                <td>Vacant Units</td>
                <td class="text-right">{{ $data['summary']['vacant'] }}</td>
                <td class="text-right">{{ $data['summary']['vacancy_rate'] }}%</td>
            </tr>
            <tr>
                <td>Under Maintenance</td>
                <td class="text-right">{{ $data['summary']['maintenance'] }}</td>
                <td class="text-right">{{ $data['summary']['total_units'] > 0 ? round(($data['summary']['maintenance'] / $data['summary']['total_units']) * 100, 1) : 0 }}%</td>
            </tr>
            <tr>
                <td>In Arrears</td>
                <td class="text-right">{{ $data['summary']['arrears'] }}</td>
                <td class="text-right">{{ $data['summary']['total_units'] > 0 ? round(($data['summary']['arrears'] / $data['summary']['total_units']) * 100, 1) : 0 }}%</td>
            </tr>
        </table>
    </div>

    @if(count($data['top_performers']) > 0)
    <div class="section">
        <h2>Top Performing Units (by Payment Consistency)</h2>
        <table>
            <tr>
                <th>Rank</th>
                <th>Unit Number</th>
                <th>Tenant Name</th>
                <th class="text-center">Collection Rate</th>
                <th class="text-center">On-Time Payments</th>
            </tr>
            @foreach($data['top_performers'] as $index => $unit)
            <tr class="{{ $index === 0 ? 'highlight' : '' }}">
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $unit['unit'] }}</td>
                <td>{{ $unit['tenant'] }}</td>
                <td class="text-center text-green">{{ $unit['collection_rate'] }}%</td>
                <td class="text-center">{{ $unit['on_time_payments'] }}/{{ $unit['total_invoices'] }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    @endif

    <div class="footer">
        <p>Generated by PropManager - Property Management System</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>
</html>
