<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Owner Statement</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { margin-bottom: 24px; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #4F46E5; font-size: 22px; }
        .header p { margin: 4px 0 0; color: #666; }
        .meta { text-align: right; font-size: 10px; color: #666; margin-bottom: 16px; }
        .section h2 { background-color: #F3F4F6; padding: 8px; margin: 0 0 12px 0; font-size: 13px; border-left: 4px solid #4F46E5; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        th, td { padding: 8px; text-align: left; border-bottom: 1px solid #E5E7EB; }
        th { background-color: #F9FAFB; font-weight: bold; }
        .text-right { text-align: right; }
        .total-row { font-weight: bold; }
        .net { font-size: 16px; font-weight: bold; color: #059669; }
        .net.neg { color: #DC2626; }
        .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #E5E7EB; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Owner Statement</h1>
        <p><strong>{{ $data['property']['name'] }}</strong></p>
        <p>Managed by {{ $landlord->name }}</p>
    </div>

    <div class="meta">
        <p><strong>Period:</strong> {{ $data['period']['start'] }} &ndash; {{ $data['period']['end'] }}</p>
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="section">
        <h2>Income</h2>
        <table>
            <tr>
                <td>Rent &amp; charges collected</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['collected'], 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2>Expenses</h2>
        <table>
            @forelse($data['expenses'] as $expense)
            <tr>
                <td>{{ $expense['category'] }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($expense['amount'], 2) }}</td>
            </tr>
            @empty
            <tr><td colspan="2">No expenses in this period.</td></tr>
            @endforelse
            <tr class="total-row">
                <td>Total expenses</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['total_expenses'], 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2>Net to Owner</h2>
        <table>
            <tr>
                <td>Collected less expenses</td>
                <td class="text-right net {{ $data['net'] < 0 ? 'neg' : '' }}">{{ $currency_symbol }} {{ number_format($data['net'], 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} - Property Management System</p>
        <p>Cash basis: payments received (excluding voided) less expenses recorded in the period. Refunds are settled separately.</p>
    </div>
</body>
</html>
