<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Remittance Advice</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { margin-bottom: 24px; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #4F46E5; font-size: 22px; }
        .header p { margin: 4px 0 0; color: #666; }
        .meta { text-align: right; font-size: 10px; color: #666; margin-bottom: 16px; }
        .section h2 { background-color: #F3F4F6; padding: 8px; margin: 0 0 12px 0; font-size: 13px; border-left: 4px solid #4F46E5; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        th, td { padding: 8px; text-align: left; border-bottom: 1px solid #E5E7EB; }
        th { background-color: #F9FAFB; font-weight: bold; }
        .text-right { text-align: right; }
        .neg { color: #DC2626; }
        .amount { font-size: 18px; font-weight: bold; color: #059669; }
        .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #E5E7EB; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Remittance Advice</h1>
        <p><strong>{{ $ownerName }}</strong></p>
        <p>From {{ $landlordName }}</p>
    </div>

    <div class="meta">
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="section">
        <h2>Payment</h2>
        <table>
            <tr>
                <td>Amount paid</td>
                <td class="text-right amount">{{ $currency_symbol }} {{ number_format((float) ($payout['amount'] ?? 0), 2) }}</td>
            </tr>
            <tr>
                <td>Date</td>
                <td class="text-right">{{ $payout['paid_on'] ?? '' }}</td>
            </tr>
            <tr>
                <td>Method</td>
                <td class="text-right">{{ $payout['method'] ?? '' }}</td>
            </tr>
            @if(! empty($payout['reference']))
            <tr>
                <td>Reference</td>
                <td class="text-right">{{ $payout['reference'] }}</td>
            </tr>
            @endif
            @if(! empty($payout['notes']))
            <tr>
                <td>Notes</td>
                <td class="text-right">{{ $payout['notes'] }}</td>
            </tr>
            @endif
        </table>
    </div>

    <div class="section">
        <h2>Account Position</h2>
        <table>
            <tr>
                <td>Net earned to date</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format((float) ($summary['lifetime_net'] ?? 0), 2) }}</td>
            </tr>
            <tr>
                <td>Total paid out to date</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format((float) ($summary['total_paid_out'] ?? 0), 2) }}</td>
            </tr>
            <tr>
                <td><strong>Balance due to you</strong></td>
                <td class="text-right {{ ($summary['balance_due'] ?? 0) < 0 ? 'neg' : '' }}">{{ $currency_symbol }} {{ number_format((float) ($summary['balance_due'] ?? 0), 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} - Property Management System</p>
        <p>This remittance advice confirms a payment made to you by your property manager.</p>
    </div>
</body>
</html>
