<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Per-Property Profit &amp; Loss</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #4F46E5; font-size: 22px; }
        .meta { text-align: right; font-size: 10px; color: #666; margin-bottom: 16px; }
        .section h2 { background-color: #F3F4F6; padding: 8px; margin: 0 0 12px 0; font-size: 13px; border-left: 4px solid #4F46E5; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        th, td { padding: 8px; text-align: left; border-bottom: 1px solid #E5E7EB; }
        th { background-color: #F9FAFB; font-weight: bold; }
        .text-right { text-align: right; }
        .neg { color: #DC2626; }
        .total-row { font-weight: bold; background-color: #F9FAFB; }
        .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #E5E7EB; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Per-Property Profit &amp; Loss</h1>
        <p>{{ $landlord->name }}</p>
    </div>

    <div class="meta">
        <p><strong>Period:</strong> {{ $data['period']['start'] }} &ndash; {{ $data['period']['end'] }}</p>
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="section">
        <h2>Profit &amp; Loss by Property (cash basis)</h2>
        <table>
            <tr>
                <th>Property</th>
                <th class="text-right">Collected</th>
                <th class="text-right">Expenses</th>
                <th class="text-right">Net</th>
                <th class="text-right">Margin</th>
            </tr>
            @foreach($data['rows'] as $row)
            <tr>
                <td>{{ $row['property'] }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($row['collected'], 2) }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($row['expenses'], 2) }}</td>
                <td class="text-right {{ $row['net'] < 0 ? 'neg' : '' }}">{{ $currency_symbol }} {{ number_format($row['net'], 2) }}</td>
                <td class="text-right">{{ $row['margin'] }}%</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td>Total ({{ $data['totals']['properties'] }} properties)</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['totals']['collected'], 2) }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['totals']['expenses'], 2) }}</td>
                <td class="text-right {{ $data['totals']['net'] < 0 ? 'neg' : '' }}">{{ $currency_symbol }} {{ number_format($data['totals']['net'], 2) }}</td>
                <td class="text-right">{{ $data['totals']['margin'] }}%</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} - Property Management System</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>
</html>
