<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Rent Roll</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #4F46E5; font-size: 22px; }
        .meta { text-align: right; font-size: 10px; color: #666; margin-bottom: 16px; }
        .section { margin-bottom: 22px; }
        .section h2 { background-color: #F3F4F6; padding: 8px; margin: 0 0 12px 0; font-size: 13px; border-left: 4px solid #4F46E5; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        th, td { padding: 6px; text-align: left; border-bottom: 1px solid #E5E7EB; }
        th { background-color: #F9FAFB; font-weight: bold; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .vacant { color: #9CA3AF; }
        .expiring { color: #D97706; font-weight: bold; }
        .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #E5E7EB; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Rent Roll</h1>
        <p>{{ $landlord->name }}</p>
    </div>

    <div class="meta">
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="section">
        <h2>Summary</h2>
        <table>
            <tr>
                <th>Units</th>
                <th class="text-center">Occupied</th>
                <th class="text-center">Vacant</th>
                <th class="text-center">Expiring (&le;60d)</th>
                <th class="text-center">Occupancy</th>
                <th class="text-right">Monthly Rent</th>
                <th class="text-right">Deposits Held</th>
                <th class="text-right">Outstanding</th>
            </tr>
            <tr>
                <td>{{ $data['totals']['units'] }}</td>
                <td class="text-center">{{ $data['totals']['occupied'] }}</td>
                <td class="text-center">{{ $data['totals']['vacant'] }}</td>
                <td class="text-center">{{ $data['totals']['expiring'] }}</td>
                <td class="text-center">{{ $data['totals']['occupancy_rate'] }}%</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['totals']['monthly_rent'], 2) }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['totals']['deposits_held'], 2) }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($data['totals']['outstanding'], 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2>Units</h2>
        <table>
            <tr>
                <th>Property</th>
                <th>Building</th>
                <th>Unit</th>
                <th>Status</th>
                <th>Tenant</th>
                <th class="text-right">Rent</th>
                <th class="text-right">Deposit</th>
                <th class="text-right">Outstanding</th>
                <th>Lease End</th>
            </tr>
            @foreach($data['rows'] as $row)
            <tr class="{{ $row['status'] === 'vacant' ? 'vacant' : ($row['status'] === 'expiring' ? 'expiring' : '') }}">
                <td>{{ $row['property'] ?? 'N/A' }}</td>
                <td>{{ $row['building'] ?? 'N/A' }}</td>
                <td>{{ $row['unit'] }}</td>
                <td>{{ ucfirst($row['status']) }}</td>
                <td>{{ $row['tenant'] ?? '—' }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($row['rent'], 2) }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($row['deposit_held'], 2) }}</td>
                <td class="text-right">{{ $currency_symbol }} {{ number_format($row['outstanding'], 2) }}</td>
                <td>{{ $row['lease_end'] ?? '—' }}</td>
            </tr>
            @endforeach
        </table>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} - Property Management System</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>
</html>
