<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Water Consumption Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #0891B2;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #0891B2;
            font-size: 24px;
        }
        .meta {
            text-align: right;
            font-size: 10px;
            color: #666;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            background-color: #CFFAFE;
            padding: 8px;
            margin: 0 0 15px 0;
            font-size: 14px;
            border-left: 4px solid #0891B2;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #E5E7EB;
        }
        th {
            background-color: #F9FAFB;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .text-cyan {
            color: #0891B2;
        }
        .info-box {
            background-color: #ECFEFF;
            border: 1px solid #67E8F9;
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 4px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #E5E7EB;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Water Consumption Report</h1>
        <p>{{ $landlord->name }}</p>
    </div>

    <div class="meta">
        <p><strong>Period:</strong> {{ ucfirst($data['period']) }}</p>
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
    </div>

    <div class="info-box">
        <strong>Total Consumption:</strong> {{ number_format($data['summary']['total_consumption'], 2) }} cubic meters<br>
        <strong>Total Cost:</strong> {{ $currency_symbol }} {{ number_format($data['summary']['total_cost'], 2) }}<br>
        <strong>Average Consumption:</strong> {{ $data['summary']['average_consumption'] }} units per reading
    </div>

    <div class="section">
        <h2>Consumption Summary</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th class="text-right">Value</th>
            </tr>
            <tr>
                <td>Total Water Consumption</td>
                <td class="text-right">{{ number_format($data['summary']['total_consumption'], 2) }} cubic meters</td>
            </tr>
            <tr>
                <td>Total Cost</td>
                <td class="text-right text-cyan">{{ $currency_symbol }} {{ number_format($data['summary']['total_cost'], 2) }}</td>
            </tr>
            <tr>
                <td>Number of Readings</td>
                <td class="text-right">{{ $data['summary']['readings_count'] }}</td>
            </tr>
            <tr>
                <td>Average Consumption per Reading</td>
                <td class="text-right">{{ $data['summary']['average_consumption'] }} units</td>
            </tr>
            <tr>
                <td>Average Cost per Reading</td>
                <td class="text-right">{{ $currency_symbol }} {{ $data['summary']['readings_count'] > 0 ? number_format($data['summary']['total_cost'] / $data['summary']['readings_count'], 2) : 0 }}</td>
            </tr>
        </table>
    </div>

    @if(count($data['top_consumers']) > 0)
    <div class="section">
        <h2>Top Water Consumers</h2>
        <table>
            <tr>
                <th>Rank</th>
                <th>Unit Number</th>
                <th class="text-right">Consumption (units)</th>
                <th class="text-right">Cost ({{ $currency_code }})</th>
            </tr>
            @foreach($data['top_consumers'] as $index => $consumer)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $consumer['unit'] }}</td>
                <td class="text-right">{{ number_format($consumer['consumption'], 2) }}</td>
                <td class="text-right text-cyan">{{ number_format($consumer['cost'], 2) }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    @endif

    <div class="footer">
        <p>Generated by {{ config('app.name') }} - Property Management System</p>
        <p>Monitor high consumers to identify potential leaks or inefficiencies.</p>
    </div>
</body>
</html>
