<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase-29 WF-LATE-FEE-3: eviction notice DRAFT — never auto-sent.
 *
 * Generated by invoices:escalate-overdue at day 30 overdue. Landlord
 * reviews, optionally edits draft_body, decides whether to mark
 * status=sent (records sent_at + the actual eviction notice mail
 * dispatch through NotificationService) or withdrawn (records
 * withdrawn_at + withdrawn_reason).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('eviction_notice_drafts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('landlord_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('lease_id')->constrained('leases')->cascadeOnDelete();
            $table->foreignId('tenant_id')->constrained('users')->cascadeOnDelete();
            $table->json('related_invoice_ids');
            $table->unsignedBigInteger('total_arrears_cents');
            $table->text('draft_body');
            $table->enum('status', ['draft', 'sent', 'withdrawn'])->default('draft');
            $table->timestamp('sent_at')->nullable();
            $table->timestamp('withdrawn_at')->nullable();
            $table->text('withdrawn_reason')->nullable();
            $table->string('source_workflow', 64);
            $table->timestamps();
            $table->index(['landlord_id', 'status'], 'end_landlord_status_idx');
            $table->index(['lease_id', 'status'], 'end_lease_status_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('eviction_notice_drafts');
    }
};
