<?php

declare(strict_types=1);

namespace App\Models;

use App\Traits\Auditable;
use App\Traits\TenantScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Phase-97 WATER-CLIENT-BILLING: a billed period for a water client (a
 * WaterConnection). The analogue of an invoice's water_due line, but lease-free —
 * keyed by the connection. Generated by WaterClientBillingService at the connection's
 * effective rate (client_rate ?? landlord water_client_rate) via the Phase-87 engine.
 */
class WaterClientCharge extends Model
{
    use Auditable, HasFactory, SoftDeletes, TenantScope;

    /** @var list<string> */
    public const STATUSES = ['due', 'partial', 'paid', 'overdue', 'voided'];

    protected $fillable = [
        'landlord_id',
        'water_connection_id',
        'billing_period_start',
        'consumption',
        'water_due',
        'amount_paid',
        'status',
        'due_date',
        'notes',
    ];

    protected $casts = [
        'billing_period_start' => 'date',
        'due_date' => 'date',
        'consumption' => 'decimal:2',
        'water_due' => 'decimal:2',
        'amount_paid' => 'decimal:2',
    ];

    public function connection(): BelongsTo
    {
        return $this->belongsTo(WaterConnection::class, 'water_connection_id');
    }

    public function landlord(): BelongsTo
    {
        return $this->belongsTo(User::class, 'landlord_id');
    }

    public function isPaid(): bool
    {
        return (float) $this->amount_paid >= (float) $this->water_due;
    }

    public function balance(): float
    {
        return max(0, round((float) $this->water_due - (float) $this->amount_paid, 2));
    }

    /**
     * Derive the lifecycle status from money + due date (voided is set explicitly).
     */
    public function deriveStatus(): string
    {
        if ($this->status === 'voided') {
            return 'voided';
        }
        if ($this->isPaid()) {
            return 'paid';
        }
        if ((float) $this->amount_paid > 0) {
            return 'partial';
        }
        if ($this->due_date !== null && $this->due_date->isPast()) {
            return 'overdue';
        }

        return 'due';
    }

    /**
     * @param  Builder<WaterClientCharge>  $query
     * @return Builder<WaterClientCharge>
     */
    public function scopeUnpaid(Builder $query): Builder
    {
        return $query->whereColumn('amount_paid', '<', 'water_due')->where('status', '!=', 'voided');
    }

    /**
     * Outstanding balance for one connection — the single source of the formula
     * (sum of positive unpaid balances), so the landlord hub + the client finances
     * surface can never drift. Keeps SoftDeletes; drops only the tenant scope.
     */
    public static function outstandingForConnection(int $connectionId): float
    {
        return round((float) static::withoutGlobalScope('landlord')
            ->where('water_connection_id', $connectionId)
            ->unpaid()
            ->selectRaw('COALESCE(SUM(GREATEST(water_due - amount_paid, 0)), 0) as bal')
            ->value('bal'), 2);
    }

    /**
     * Outstanding balance per connection for a landlord, batched (no N+1).
     *
     * @return \Illuminate\Support\Collection<int, float>
     */
    public static function outstandingByConnection(int $landlordId): \Illuminate\Support\Collection
    {
        return static::withoutGlobalScope('landlord')
            ->where('landlord_id', $landlordId)
            ->unpaid()
            ->selectRaw('water_connection_id, ROUND(COALESCE(SUM(GREATEST(water_due - amount_paid, 0)), 0), 2) as balance')
            ->groupBy('water_connection_id')
            ->pluck('balance', 'water_connection_id');
    }
}
